---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openstack-assistant
  namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstack-assistant-role
rules:
  # openstackversion - read, patch, update
  - apiGroups: ["core.openstack.org"]
    resources: ["openstackversions"]
    verbs: ["get", "list", "watch", "patch", "update"]

  # openstackcontrolplane - view/list
  - apiGroups: ["core.openstack.org"]
    resources: ["openstackcontrolplanes"]
    verbs: ["get", "list", "watch"]

  # openstackdataplanenodeset - view/list
  - apiGroups: ["dataplane.openstack.org"]
    resources: ["openstackdataplanenodesets"]
    verbs: ["get", "list", "watch"]

  # openstackdataplanedeployments - read, patch, create
  - apiGroups: ["dataplane.openstack.org"]
    resources: ["openstackdataplanedeployments"]
    verbs: ["get", "list", "watch", "patch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openstack-assistant-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openstack-assistant-role
subjects:
  - kind: ServiceAccount
    name: openstack-assistant
    namespace: openstack
